### ISSUE TITLE
add yarn.lock or package-lock.json

### ISSUE THREAD

**Issue by jingzhou123** [phosphorjs/phosphor-gridpanel#3]
got many errs:

npm run build

> phosphor-gridpanel@1.0.0-beta.1 build /workspace/phosphor-gridpanel
> npm run build:src && npm run build:test && npm run build:css

> phosphor-gridpanel@1.0.0-beta.1 build:src /workspace/phosphor-gridpanel
> tsc --project src

src/index.ts(31,3): error TS2305: Module '"/workspace/phosphor-gridpanel/node_modules/phosphor-widget/lib/index"' has no exported member 'ChildIndexMessage'.
src/index.ts(31,36): error TS2305: Module '"/workspace/phosphor-gridpanel/node_modules/phosphor-widget/lib/index"' has no exported member 'Panel'.
src/index.ts(100,37): error TS2345: Argument of type 'GridPanel' is not assignable to parameter of type 'IMessageHandler'.
src/index.ts(117,37): error TS2345: Argument of type 'GridPanel' is not assignable to parameter of type 'IMessageHandler'.
src/index.ts(305,10): error TS2339: Property 'addClass' does not exist on type 'GridPanel'.
src/index.ts(403,10): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(404,14): error TS2339: Property 'isAttached' does not exist on type 'GridPanel'.
src/index.ts(405,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
    Property 'processMessage' is missing in type 'GridPanel'.
src/index.ts(417,14): error TS2339: Property 'isAttached' does not exist on type 'GridPanel'.
src/index.ts(418,10): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(427,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(435,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(442,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(449,14): error TS2339: Property 'isVisible' does not exist on type 'GridPanel'.
src/index.ts(450,40): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(451,42): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(460,14): error TS2339: Property 'isVisible' does not exist on type 'GridPanel'.
src/index.ts(461,33): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(461,56): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(469,14): error TS2339: Property 'isAttached' does not exist on type 'GridPanel'.
src/index.ts(501,30): error TS2339: Property 'childCount' does not exist on type 'GridPanel'.
src/index.ts(502,25): error TS2339: Property 'childAt' does not exist on type 'GridPanel'.
src/index.ts(513,32): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(520,22): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(527,14): error TS2339: Property 'parent' does not exist on type 'GridPanel'.
src/index.ts(527,39): error TS2339: Property 'parent' does not exist on type 'GridPanel'.
src/index.ts(530,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(538,14): error TS2339: Property 'childCount' does not exist on type 'GridPanel'.
src/index.ts(543,56): error TS2339: Property 'node' does not exist on type 'GridPanel'.
src/index.ts(553,32): error TS2339: Property 'childCount' does not exist on type 'GridPanel'.
src/index.ts(554,27): error TS2339: Property 'childAt' does not exist on type 'GridPanel'.
src/index.ts(588,30): error TS2339: Property 'childCount' does not exist on type 'GridPanel'.
src/index.ts(590,25): error TS2339: Property 'childAt' does not exist on type 'GridPanel'.
src/index.ts(626,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(643,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(650,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
src/index.ts(657,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
  Type 'GridPanel' is not assignable to type 'IMessageHandler'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phosphor-gridpanel@1.0.0-beta.1 build:src: `tsc --project src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phosphor-gridpanel@1.0.0-beta.1 build:src script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2019-07-18T05_03_29_307Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phosphor-gridpanel@1.0.0-beta.1 build: `npm run build:src && npm run build:test && npm run build:css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phosphor-gridpanel@1.0.0-beta.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2019-07-18T05_03_29_328Z-debug.log

**Comment by sccolbert** [comment]
This repository is old, umaintained code. You should use the packages here:
https://github.com/phosphorjs/phosphor

**Comment by vidartf** [comment]
@sccolbert You could consider "archiving" this repository: https://help.github.com/en/articles/archiving-repositories
